[package]
name = "teko"
version = "0.1.0"
authors = ["Kevin Robert Stravers <macocio@gmail.com>"]

[dependencies]
clippy = {version = "*", optional = true}
num = "0.1.37"
num-traits = "0.1.37"

[profile.release]
debug = true


[features]
default = []
